### ISSUE TITLE
how do i return the ID of the saved vertice ?

### ISSUE THREAD

**Issue by afidegnum** [dpapathanasiou/simple-graph#12]
is there a way to save a vertex and return it's id?

**Comment by ope-nz** [comment]
You supply the id, the database does not assign new ids.

**Comment by dpapathanasiou** [comment]
Hi @afidegnum and sorry for not getting back to you sooner

@ope-nz is right, part of the magic of this setup, using a generated column for the id means that you need to have defined it within the json body of the node, so you already "know" it.

But if all you're asking is how to have the id returned upon successful insert, similar to how [RETURNING in PostgreSQL](https://www.postgresql.org/docs/current/dml-returning.html) works, there's no built-in support for that in sqlite.

So instead, you could modify the functions to return it, if you want.
