### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by joshday** [dpapathanasiou/simple-graph#13]
Hey,

This isn't an issue, just wanted to say thanks for creating simple-graph!

I used it as the basis for a Julia package (https://github.com/joshday/SQLiteGraph.jl), since as far as I know, there's no graph database that has a Julia interface.  I made some minor changes tailored to my specific use case, but I wouldn't have been able to put it together so easily without the help of your work, so thanks again!

**Comment by dpapathanasiou** [comment]
Thank you @joshday 

I've just updated the README to add a link to the julia implementation
