### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by rodydavis** [dpapathanasiou/simple-graph#15]
Here is a flutter example i created and runs SQLite on all the platforms it exports to!

https://github.com/rodydavis/flutter_graph_database

**Comment by dpapathanasiou** [comment]
Hi @rodydavis and thanks for letting me know!

The [demo page](https://rodydavis.github.io/flutter_graph_database/) does not seem to load for me, though; according to the browser console, there's a minification error in the main script:

```
Uncaught Error: Instance of 'minified:a2' 2 main.dart.js:4026:3
    c https://rodydavis.github.io/flutter_graph_database/main.dart.js:4026
    ajl https://rodydavis.github.io/flutter_graph_database/main.dart.js:6098
    $0 https://rodydavis.github.io/flutter_graph_database/main.dart.js:30157
    aoQ https://rodydavis.github.io/flutter_graph_database/main.dart.js:5372
    ap9 https://rodydavis.github.io/flutter_graph_database/main.dart.js:5374
    $1 https://rodydavis.github.io/flutter_graph_database/main.dart.js:29378
    aqD https://rodydavis.github.io/flutter_graph_database/main.dart.js:4107
    s https://rodydavis.github.io/flutter_graph_database/main.dart.js:4115
```

**Comment by rodydavis** [comment]
Gotcha! May have been an issue on my side. It was working in dev mode at least

**Comment by dpapathanasiou** [comment]
Ha, [of course](https://drivendata.co/images/works-on-my-machine.jpg) :)

Anyway, I admit I'd never heard of Flutter and Dart before you posted this, so thank you again for the heads-up.

In the meantime, I've updated the README to [include a reference to it](https://github.com/dpapathanasiou/simple-graph/commit/6278a929c5a748a30360588806b3b906bba284db), so I'll mark this "issue" as closed.
