### ISSUE TITLE
Feature request: Color properties for visualizations on Edges & Nodes

### ISSUE THREAD

**Issue by lancilloty** [dpapathanasiou/simple-graph#19]
Would it be possible to add color properties for the visualizations of edges & nodes? Graphviz supports it for the python colors: https://graphviz.org/doc/info/colors.html

I'm not sure about the other languages then python but I'm sure I wouldn't be alone to want colors in graphs to ease their use when they become large.

**Comment by dpapathanasiou** [comment]
Hi @lancilloty 

The great thing about the schema is that both the node bodies and the edge properties allow any valid json.

So all you have to do is include a key value pair like `"fillcolor": "cyan"` in the node bodies, and then the [visualizer](https://github.com/dpapathanasiou/simple-graph-pypi/blob/main/src/simple_graph_sqlite/visualizers.py) function (the python implementation has moved [here](https://github.com/dpapathanasiou/simple-graph-pypi), BTW) should be able to represent that as a [node attribute](https://graphviz.org/docs/nodes/) without any further modification.

That's just off the top of my head though, I haven't tried it, and you might need a slight tweak to either the [_as_dot_label](https://github.com/dpapathanasiou/simple-graph-pypi/blob/main/src/simple_graph_sqlite/visualizers.py#L16) or [_as_dot_node](https://github.com/dpapathanasiou/simple-graph-pypi/blob/main/src/simple_graph_sqlite/visualizers.py#L23) functions to get it to work.

Feel free to [file a request](https://github.com/dpapathanasiou/simple-graph-pypi/issues) there if it doesn't pick it up automatically.
