### ISSUE TITLE
Error initializing database

### ISSUE THREAD

**Issue by mrdcbrush** [dpapathanasiou/simple-graph#2]
Context: MacOS Mojave, SQLite3, Python 3.8.5

The default sqlite3 binary in MacOS Mojave does not have the JSON extensions enabled.

Fix:
Install sqlite via brew
Add to shell initialization file:  export PATH="/usr/local/opt/sqlite/bin:$PATH"

**Comment by dpapathanasiou** [comment]
Thank you @mrdcbrush for pointing it out. 

I've updated the README with the minimum version required in a9d250ad346c2bd4e0a229819767fed7f464115d

**Comment by bansalnaman15** [comment]
I am using Windows. Can anybody help?_
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    db.initialize(apple)
  File "C:\Users\Naman\Downloads\simple-graph-main\simple-graph-main\database.py", line 30, in initialize
    return atomic(db_file, _init)
  File "C:\Users\Naman\Downloads\simple-graph-main\simple-graph-main\database.py", line 20, in atomic
    results = cursor_exec_fn(cursor)
  File "C:\Users\Naman\Downloads\simple-graph-main\simple-graph-main\database.py", line 29, in _init
    cursor.execute(statement)
sqlite3.OperationalError: near "AS": syntax error

**Comment by dpapathanasiou** [comment]
Hi @bansalnaman15 

Which versions of python and sqlite do you have?

Python should be 3.x and sqlite should be at least 3.3.1.

Here is my current setup:

```sh
$ python -V
Python 3.7.9
$ sqlite3 -version
3.33.0 2020-08-14 13:23:32 fca8dc8b578f215a969cd899336378966156154710873e68b3d9ac5881b0alt2
```

**Comment by bansalnaman15** [comment]
Got this working by conda environment. Thankyou so much.
