### ISSUE TITLE
Any plans for a deno driver?

### ISSUE THREAD

**Issue by chovy** [dpapathanasiou/simple-graph#6]

**Comment by dpapathanasiou** [comment]
This [deno](https://deno.land/)?

The latest release [separates the schema and prepared statements](https://github.com/dpapathanasiou/simple-graph/tree/main/sql) so they can be read and used by programs in any programming language with SQLite bindings.

**Comment by dpapathanasiou** [comment]
I'm not into javascript myself, but I've restructured it to [accommodate multiple implementations](https://github.com/dpapathanasiou/simple-graph#usage) so if you're up for contributing it, I'd welcome your pull request.
