### ISSUE TITLE
Multiple Node Connections in visualize

### ISSUE THREAD

**Issue by defaltus** [dpapathanasiou/simple-graph#7]
If I am having a graph with multiple nodes attached to a single node (e.g. node 7), the command ```db.visualize(graph, 'example.dot', db.traverse(graph, 7, neighbors_fn=db.find_outbound_neighbors))``` only visualizes the first connection found in ```db.find_outbound_neighbors```. Is there a way to automatically visualize all connections?

**Comment by dpapathanasiou** [comment]
Check out the latest release: I switched to using [Common Table Expressions](https://github.com/dpapathanasiou/simple-graph#structure) for the traversals.

**Comment by defaltus** [comment]
Still the same problem, maybe I am doing something wrong. When I want to visualize the apple example with ```db.visualize(apple, 'apple.dot', path=[1, 2, 3, 4, 5])``` I only get the following links:

![](https://i.imgur.com/DU3Iaro.png)

However, all the links to Apple Company should get visualized, shouldn't they?

**Comment by dpapathanasiou** [comment]
Ah, you were right: the pairwise `(src, tgt)` iteration in the visualize function was wrong, so I updated the corresponding query, and collected the nodes and edges differently.

So now it works as you would expect.
