### ISSUE TITLE
Find Node

### ISSUE THREAD

**Issue by chhenning** [dpapathanasiou/simple-graph#9]
Why do you use `fetchall()` and not `fetchone()`?

https://github.com/dpapathanasiou/simple-graph/blob/be41db28995f745a4f85677bcade7f0471984848/python/database.py#L112

**Comment by dpapathanasiou** [comment]
I noticed this in the [prior issue](https://github.com/dpapathanasiou/simple-graph/issues/8#issuecomment-857254159): the [find node query](https://github.com/dpapathanasiou/simple-graph/blob/main/sql/search-node-by-id.sql) does *not* query on the unique id field, as it should.

So instead of this:

```sql
SELECT body FROM nodes WHERE json_extract(body, '$.id') = ?
```

It does this, and therefore returns a list like every other type of search:

```sql
SELECT body FROM nodes WHERE id = ?
```
Editing the sql is simple enough (and I should perhaps just do it), but then I'll also need to tweak that function (and the corresponding [one in go](https://github.com/dpapathanasiou/simple-graph/blob/main/go/simplegraph/database.go#L273)) to handle the `not found` case better.

**Comment by chhenning** [comment]
I did the change in my copy and it seems to work quite nicely. I'm only interested in the `Python` version. So, I cannot really speak to the `Go` version.

BTW,  I know this is offtopic but I added `IGNORE` in my insert statements. I'm too lazy to always check if a node already exists. ;-)

```sql
INSERT OR IGNORE INTO nodes VALUES(json(?))
```

**Comment by dpapathanasiou** [comment]
> I did the change in my copy and it seems to work quite nicely. I'm only interested in the `Python` version. So, I cannot really speak to the `Go` version.

Yes, I'm going to make the same update too, but I want to keep both implementations in sync; this project is to show that it's about the sql primarily, and it'll work with any programming language with [SQLite bindings](https://en.wikipedia.org/wiki/SQLite#Programming_language_support).

Though I too prefer python as a practical matter: strongly typed languages like Go make working with json difficult, and python is just better in that regard.

> 
> BTW, I know this is offtopic but I added `IGNORE` in my insert statements. I'm too lazy to always check if a node already exists. ;-)
> 
> ```sql
> INSERT OR IGNORE INTO nodes VALUES(json(?))
> ```

That's interesting, are you not concerned with potentially messing up the referential integrity of the edges? I'd love to know more about how you're using it.

**Comment by chhenning** [comment]
Regarding the `IGNORE`. When you load your data into the tables you always faced with a decision what to do when you have duplicates. There are several ways to deal with that. In python, there is `EAFP versus LBYL`. Have a look here:

https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/

So, when adding a new node we could:

1. Have a look if exists already and if not then insert.
2. Ignore an exception thrown by sqlite in case the node already exists.
3. Use the IGNORE keyword in the sql INSERT to tell sqlite to ignore conflicts when inserting a new node.

Granted it depends a little on the application but in my case, I'm fine with `IGNORE`.

**Comment by dpapathanasiou** [comment]
It's interesting how those idioms vary by language.

According to "Effective Java", for example, using try/catch for the "eafp" approach is considered bad form, and should be avoided.

The only reason I prefer "lbyl" when it comes to inserting nodes is it maintains the referential integrity of the edges: i.e., if you over-write an existing node, you'll also assume the existing connections in and out, which may not be correct.

P.S. I'm launching a modified version of this project as a cloud-based service. Let me know if you'd be interested in being a (free) trial user.
